# Generated by Django 5.0 on 2025-02-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='saved_audio/')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
