# Generated by Django 5.0 on 2025-02-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_savednews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savednews',
            options={'verbose_name_plural': 'Saved News'},
        ),
        migrations.RenameField(
            model_name='savednews',
            old_name='saved_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='savednews',
            name='audio',
        ),
        migrations.AddField(
            model_name='savednews',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='savednews',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
